[package]
name = "mcsr-setup"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { version = "0.13.1", features = ["advanced"] }
mcsr-setup-core = { version = "0.1.0", path = "mcsr-setup-core" }
