[package]
name = "mcsr-setup-core"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { version = "0.13.1", features = ["advanced"] }
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
